### ISSUE TITLE
FF4 - Exception: No default or local profile has been set.

### ISSUE THREAD

**Issue by benpink** [windmill/windmill#72]
Having trouble getting windmill going with firefox4 and any version of Windmill. I've tried v1.6, 1.4 and latest 1.7 from source. All result in the same error:

ben@vm-ubuntu:~$ windmill firefox "http://google.com"
Traceback (most recent call last):
  File "/usr/local/bin/windmill", line 9, in <module>
    load_entry_point('windmill==1.6', 'console_scripts', 'windmill')()
  File "/usr/local/lib/python2.7/dist-packages/windmill-1.6-py2.7.egg/windmill/bin/windmill_bin.py", line 33, in main
    admin_lib.command_line_startup()
  File "/usr/local/lib/python2.7/dist-packages/windmill-1.6-py2.7.egg/windmill/bin/admin_lib.py", line 351, in command_line_startup
    shell_objects = setup()
  File "/usr/local/lib/python2.7/dist-packages/windmill-1.6-py2.7.egg/windmill/bin/admin_lib.py", line 182, in setup
    shell_objects_dict['browser'] = getattr(shell_objects, browser[0].lower())()
  File "/usr/local/lib/python2.7/dist-packages/windmill-1.6-py2.7.egg/windmill/bin/shell_objects.py", line 45, in start_firefox
    controller = windmill.browser.get_firefox_controller()
  File "/usr/local/lib/python2.7/dist-packages/windmill-1.6-py2.7.egg/windmill/browser/**init**.py", line 116, in get_firefox_controller
    controller = mozrunner.get_moz_from_settings(copy.copy(windmill.settings))
  File "/usr/local/lib/python2.7/dist-packages/windmill-1.6-py2.7.egg/windmill/dep/_mozrunner/__init__.py", line 165, in get_moz_from_settings
    cmd_args=settings['MOZILLA_CMD_ARGS'])
  File "/usr/local/lib/python2.7/dist-packages/windmill-1.6-py2.7.egg/windmill/dep/_mozrunner/__init__.py", line 131, in get_moz
    raise Exception ('No default or local profile has been set.')
Exception: No default or local profile has been set.

**Comment by elboletaire** [comment]
Shouldn't this be in the docs? I've just got the same error.
